package input

type InputIDItem struct {
	ID int `uri:"id" binding:"required"`
}

type ItemInput struct {
	KodeProduk string `json:"kode_produk"`
	Jenis      string `json:"jenis"`
	Kategori   string `json:"kategori"`
	Satuan     string `json:"satuan"`
	NamaProduk string `json:"nama_produk"`
	Keterangan string `json:"keterangan"`
	Lokasi     string `json:"lokasi"`
	Gambar     string `json:"gambar"`
	HargaJual  int    `json:"harga_jual"`
	Stok       int    `json:"stok"`
}

type InputFilter struct {
	Filter string `json:"filter"`
}

//Generated by Micagen at 08 Desember 2021
