package input

type InputIDLokasi struct { 
ID int `uri:"id" binding:"required"` 
}

type LokasiInput struct { 
KodeLokasi string `json:"kode_lokasi"` 
Lokasi string `json:"lokasi"` 
}

//Generated by Micagen at 08 Desember 2021