package service

import (
	"github.com/ekokurniadi/pos-golang/entity"
	"github.com/ekokurniadi/pos-golang/input"
	"github.com/ekokurniadi/pos-golang/repository"
)

type JenisService interface {
	JenisServiceGetAll() ([]entity.Jenis, error)
	JenisServiceGetByID(inputID input.InputIDJenis) (entity.Jenis, error)
	JenisServiceCreate(input input.JenisInput) (entity.Jenis, error)
	JenisServiceUpdate(inputID input.InputIDJenis, inputData input.JenisInput) (entity.Jenis, error)
	JenisServiceDeleteByID(inputID input.InputIDJenis) (bool, error)
}
type jenisService struct {
	repository repository.JenisRepository
}

func NewJenisService(repository repository.JenisRepository) *jenisService {
	return &jenisService{repository}
}
func (s *jenisService) JenisServiceCreate(input input.JenisInput) (entity.Jenis, error) {
	jenis := entity.Jenis{}
	jenis.Jenis = input.Jenis
	newJenis, err := s.repository.SaveJenis(jenis)
	if err != nil {
		return newJenis, err
	}
	return newJenis, nil
}
func (s *jenisService) JenisServiceUpdate(inputID input.InputIDJenis, inputData input.JenisInput) (entity.Jenis, error) {
	jenis, err := s.repository.FindByIDJenis(inputID.ID)
	if err != nil {
		return jenis, err
	}
	jenis.Jenis = inputData.Jenis

	updatedJenis, err := s.repository.UpdateJenis(jenis)

	if err != nil {
		return updatedJenis, err
	}
	return updatedJenis, nil
}
func (s *jenisService) JenisServiceGetByID(inputID input.InputIDJenis) (entity.Jenis, error) {
	jenis, err := s.repository.FindByIDJenis(inputID.ID)
	if err != nil {
		return jenis, err
	}
	return jenis, nil
}
func (s *jenisService) JenisServiceGetAll() ([]entity.Jenis, error) {
	jeniss, err := s.repository.FindAllJenis()
	if err != nil {
		return jeniss, err
	}
	return jeniss, nil
}
func (s *jenisService) JenisServiceDeleteByID(inputID input.InputIDJenis) (bool, error) {
	_, err := s.repository.FindByIDJenis(inputID.ID)
	if err != nil {
		return false, err
	}
	_, err = s.repository.DeleteByIDJenis(inputID.ID)
	if err != nil {
		return false, err
	}
	return true, nil
}

//Generated by Micagen at 08 Desember 2021
