package formatter

import "github.com/ekokurniadi/pos-golang/entity"

type ItemFormatter struct {
	ID         int    `json:"id"`
	KodeProduk string `json:"kode_produk"`
	Jenis      string `json:"jenis"`
	Kategori   string `json:"kategori"`
	Satuan     string `json:"satuan"`
	NamaProduk string `json:"nama_produk"`
	Keterangan string `json:"keterangan"`
	Lokasi     string `json:"lokasi"`
	Gambar     string `json:"gambar"`
	HargaJual  int    `json:"harga_jual"`
	Stok       int    `json:"stok"`
}

func FormatItem(item entity.Item) ItemFormatter {
	itemFormatter := ItemFormatter{}
	itemFormatter.ID = item.ID
	itemFormatter.KodeProduk = item.KodeProduk
	itemFormatter.Jenis = item.Jenis
	itemFormatter.Kategori = item.Kategori
	itemFormatter.Satuan = item.Satuan
	itemFormatter.NamaProduk = item.NamaProduk
	itemFormatter.Keterangan = item.Keterangan
	itemFormatter.Lokasi = item.Lokasi
	itemFormatter.Gambar = item.Gambar
	itemFormatter.HargaJual = item.HargaJual
	itemFormatter.Stok = item.Stok
	return itemFormatter
}
func FormatItems(items []entity.Item) []ItemFormatter {
	itemsFormatter := []ItemFormatter{}
	for _, item := range items {
		itemFormatter := FormatItem(item)
		itemsFormatter = append(itemsFormatter, itemFormatter)
	}
	return itemsFormatter
}

//Generated by Micagen at 08 Desember 2021
