package formatter

import "github.com/ekokurniadi/pos-golang/entity"

type JenisFormatter struct {
	ID    int    `json:"id"`
	Jenis string `json:"jenis"`
}

func FormatJenis(jenis entity.Jenis) JenisFormatter {
	jenisFormatter := JenisFormatter{}
	jenisFormatter.ID = jenis.ID
	jenisFormatter.Jenis = jenis.Jenis
	return jenisFormatter
}
func FormatJeniss(jeniss []entity.Jenis) []JenisFormatter {
	jenissFormatter := []JenisFormatter{}
	for _, jenis := range jeniss {
		jenisFormatter := FormatJenis(jenis)
		jenissFormatter = append(jenissFormatter, jenisFormatter)
	}
	return jenissFormatter
}

//Generated by Micagen at 08 Desember 2021
