package formatter

import "github.com/ekokurniadi/pos-golang/entity"

type KategoriFormatter struct {
	ID       int    `json:"id"`
	Kategori string `json:"kategori"`
}

func FormatKategori(kategori entity.Kategori) KategoriFormatter {
	kategoriFormatter := KategoriFormatter{}
	kategoriFormatter.ID = kategori.ID
	kategoriFormatter.Kategori = kategori.Kategori
	return kategoriFormatter
}
func FormatKategoris(kategoris []entity.Kategori) []KategoriFormatter {
	kategorisFormatter := []KategoriFormatter{}
	for _, kategori := range kategoris {
		kategoriFormatter := FormatKategori(kategori)
		kategorisFormatter = append(kategorisFormatter, kategoriFormatter)
	}
	return kategorisFormatter
}

//Generated by Micagen at 08 Desember 2021
