package formatter

import "github.com/ekokurniadi/pos-golang/entity"

type LokasiFormatter struct {
	ID         int    `json:"id"`
	KodeLokasi string `json:"kode_lokasi"`
	Lokasi     string `json:"lokasi"`
}

func FormatLokasi(lokasi entity.Lokasi) LokasiFormatter {
	lokasiFormatter := LokasiFormatter{}
	lokasiFormatter.ID = lokasi.ID
	lokasiFormatter.KodeLokasi = lokasi.KodeLokasi
	lokasiFormatter.Lokasi = lokasi.Lokasi
	return lokasiFormatter
}
func FormatLokasis(lokasis []entity.Lokasi) []LokasiFormatter {
	lokasisFormatter := []LokasiFormatter{}
	for _, lokasi := range lokasis {
		lokasiFormatter := FormatLokasi(lokasi)
		lokasisFormatter = append(lokasisFormatter, lokasiFormatter)
	}
	return lokasisFormatter
}

//Generated by Micagen at 08 Desember 2021
