package formatter

import "github.com/ekokurniadi/pos-golang/entity"

type SatuanFormatter struct {
	ID     int    `json:"id"`
	Satuan string `json:"satuan"`
}

func FormatSatuan(satuan entity.Satuan) SatuanFormatter {
	satuanFormatter := SatuanFormatter{}
	satuanFormatter.ID = satuan.ID
	satuanFormatter.Satuan = satuan.Satuan
	return satuanFormatter
}
func FormatSatuans(satuans []entity.Satuan) []SatuanFormatter {
	satuansFormatter := []SatuanFormatter{}
	for _, satuan := range satuans {
		satuanFormatter := FormatSatuan(satuan)
		satuansFormatter = append(satuansFormatter, satuanFormatter)
	}
	return satuansFormatter
}

//Generated by Micagen at 08 Desember 2021
